### ISSUE TITLE
弹幕姬失效了

### ISSUE THREAD

**Issue by imba97** [BanqiJane/BiliLiveChat#3]
不知道阿B改了啥，弹幕获取不到了，人气值是有的

![image](https://user-images.githubusercontent.com/10150208/171856035-c97bef9e-e044-43af-a17b-fc36bad46b75.png)

![image](https://user-images.githubusercontent.com/10150208/171856172-86ae5c89-02e4-46e3-9338-ee79ffda2647.png)

**Comment by imba97** [comment]
哦豁 是 `cmd` 的格式变了

![image](https://user-images.githubusercontent.com/10150208/171857835-d59f01d4-a874-445b-8bb3-3d6a77523b90.png)

目前只发现 `DANMU_MSG` 变了，其他应该没问题

![image](https://user-images.githubusercontent.com/10150208/171857998-dfb94a39-5aa0-407b-9760-7c551b61832a.png)

**Comment by BanqiJane** [comment]
哦  破站每一年都有的'特殊时期'， 貌似这个时期全网都不会显示弹幕的 ， 你细心观察 破站没有弹幕显示了， 貌似昨天恢复正常了 我这里没做处理   加个.startsWith("DANMU_MSG")函数 过滤就好了
